### ISSUE TITLE
Find shortcuts will be broken in Brackets 1.0

### ISSUE THREAD

**Issue by peterflynn** [ahmadnazir/brackets-emacs#11]
The deprecated Command ids `EDIT_FIND`, `EDIT_FIND_NEXT`, and `EDIT_FIND_PREVIOUS` are used by your extension, but they have been removed in the next release of Brackets (Brackets 1.0, which will be released in 3-4 days).

I think most of your extension will keep working, but the search keyboard shortcuts will not work because you're referencing command ids that no longer exist.

**Comment by ahmadnazir** [comment]
This is not relevant anymore since the obsolete commands are not being referenced.
