### ISSUE TITLE
list of shorcuts available?

### ISSUE THREAD

**Issue by edjroz** [ahmadnazir/brackets-emacs#13]
what are the keybindings available in this extension?

**Comment by ahmadnazir** [comment]
Have a look at the main.js file at https://github.com/ahmadnazir/brackets-emacs/blob/master/main.js#L15 for a list of commands.

Or if you want to see the key bindings instead of the names, have a looks here:
https://github.com/ahmadnazir/brackets-emacs/blob/master/main.js#L304
