### ISSUE TITLE
M-f activate the Brackets native menu

### ISSUE THREAD

**Issue by rococtz** [ahmadnazir/brackets-emacs#17]
When trying to use the M-f binding (forward word) in Brackets for Windows, the cursor jumps to the next word, as expected, but it becomes inactive because of the Brackets native menu.

In Brackets for Windows, Alt + F also means activate the File menu. 

M-b works just fine because there's no menu starting with the B letter. This means that none of these bindings will work properly: M-f (File menu), M-e (Edit menu) and so on.

Any idea where to start looking for a fix?

**Comment by blackmiaool** [comment]
Seems they'll fix it in 1.10 https://github.com/adobe/brackets/issues/12782

**Comment by ahmadnazir** [comment]
Needless to say, it has been a while that I have stopped maintaining this extension. Checkout the forks for more activity. This project will be archived soon.
