### ISSUE TITLE
Ctrl-D not mapped to anything...

### ISSUE THREAD

**Issue by breitling** [ahmadnazir/brackets-emacs#18]
I starting using your brackets extension for emacs key bindings and I quickly noticed nothing was bound to Ctrl-D, which is normally bound to delete-character-after in an emacs editor. I cloned your repository and fixed the issue on my local extension. I have the edits, but I can't push my changes to a pull requests. I new at this, so I'm probably just not doing this the proper way.

I tried to do a 'git push origin my-local-branch' but I was denied permission to your repo.

**Comment by breitling** [comment]
46d45
<         DELETE_CHAR_AFTER       = "emacs.delete-char-after",
277d275
<
291d288
<
298,310d294
<     function deleteCharAfter() {
<         var editor      = EditorManager.getFocusedEditor();
<         var doc = editor.document;
<         var start = editor.getCursorPos(),
<             end = editor.getCursorPos();
<
<         end.ch++;
<
< //      _killRingSave(doc.getRange(start, end));
<
<         doc.replaceRange("", start, end);
<     }
<
542,547d525
<                 {
<                     id: DELETE_CHAR_AFTER,
<                     name: "Delete Character After",
<                     key: "Ctrl-D",
<                     callback: deleteCharAfter.bind(this)
<                 },

**Comment by breitling** [comment]
45a46
>         DELETE_CHAR_AFTER       = "emacs.delete-char-after",
275a277
>
288a291
>
294a298,310
>     function deleteCharAfter() {
>         var editor      = EditorManager.getFocusedEditor();
>         var doc = editor.document;
>         var start = editor.getCursorPos(),
>             end = editor.getCursorPos();
>
>         end.ch++;
>
> //      _killRingSave(doc.getRange(start, end));
>
>         doc.replaceRange("", start, end);
>     }
>
526c542,548
<
---
>                 {
>                     id: DELETE_CHAR_AFTER,
>                     name: "Delete Character After",
>                     key: "Ctrl-D",
>                     callback: deleteCharAfter.bind(this)
>                 },
>

**Comment by breitling** [comment]
`45a46
>         DELETE_CHAR_AFTER       = "emacs.delete-char-after",
275a277
>
288a291
>
294a298,310
>     function deleteCharAfter() {
>         var editor      = EditorManager.getFocusedEditor();
>         var doc = editor.document;
>         var start = editor.getCursorPos(),
>             end = editor.getCursorPos();
>
>         end.ch++;
>
> //      _killRingSave(doc.getRange(start, end));
>
>         doc.replaceRange("", start, end);
>     }
>
526c542,548
<
---
>                 {
>                     id: DELETE_CHAR_AFTER,
>                     name: "Delete Character After",
>                     key: "Ctrl-D",
>                     callback: deleteCharAfter.bind(this)
>                 },
>
`

**Comment by breitling** [comment]
<pre>
45a46
>         DELETE_CHAR_AFTER       = "emacs.delete-char-after",
275a277
>
288a291
>
294a298,310
>     function deleteCharAfter() {
>         var editor      = EditorManager.getFocusedEditor();
>         var doc = editor.document;
>         var start = editor.getCursorPos(),
>             end = editor.getCursorPos();
>
>         end.ch++;
>
> //      _killRingSave(doc.getRange(start, end));
>
>         doc.replaceRange("", start, end);
>     }
>
526c542,548
<
---
>                 {
>                     id: DELETE_CHAR_AFTER,
>                     name: "Delete Character After",
>                     key: "Ctrl-D",
>                     callback: deleteCharAfter.bind(this)
>                 },
>
</pre>

**Comment by ahmadnazir** [comment]
Hi Bob,

Thanks for taking time to contribute back.

You will have to push the changes to your own fork. Once that is done, you will see that you can create a pull request from the interface.

Cheers!
