### ISSUE TITLE
Ctrl-L to center buffer?

### ISSUE THREAD

**Issue by Taariqq** [ahmadnazir/brackets-emacs#20]
How do I map 'Ctrl-L' to center the buffer at cursor point? I am trying to hack the 'keymap.json' file but do not know how to word it; "Ctrl-L": "emacs.center.something?"

**Comment by ahmadnazir** [comment]
Sorry for the delay.

The command is called `recenter-top-bottom`. You can find the command names in emacs your self by running the following: `M-x describe-key` and then pressing the keys e.g. `Ctrl-L` and you'll get the documentation for that command (including the name of course).

Hope that helps!
